# Generated by Django 2.0.2 on 2019-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='resume',
            field=models.ImageField(upload_to='resume'),
        ),
    ]
